
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Scanner;

public class Demo {

    public static void main(String[] args) {

        Scanner in = new Scanner(System.in);

        while (true) {

            // ===== MAIN MENU =====
            System.out.println("\n==== Main Menu ====");
            System.out.println("P. Patient Menu");
            System.out.println("D. Drug Menu");
            System.out.println("X. Exit");
            System.out.print("Enter choice: ");

            String choice = in.nextLine().toUpperCase();

            switch (choice) {

                // Menu if pateint option chosen
                case "P":
                    System.out.println("\n==== Patient Menu ====");
                    System.out.println("A. Write patient info to database");
                    System.out.println("B. Read patient info from database");
                    System.out.println("C. Write patient info to text file");
                    System.out.println("D. Read patient info from text file");
                    System.out.print("Enter choice: ");

                    String patientChoice = in.nextLine().toUpperCase();

                    switch (patientChoice) {

                        case "A":
                            // writePatientDB();
                            System.out.println("Writing patient info to DB...");
                            break;

                        case "B":
                            // readPatientDB();
                            System.out.println("Reading patient info from DB...");
                            break;

                        case "C":
                            // writePatientFile();
                            System.out.println("Writing patient info to file...");
                            break;

                        case "D":
                            // readPatientFile();
                            System.out.println("Reading patient info from file...");
                            break;

                        default:
                            System.out.println("Invalid patient menu choice.");
                            break;
                    }
                    break;

                // Menu if drug option chosen
                case "D":
                    System.out.println("\n==== Drug Menu ====");
                    System.out.println("A. Write drug info to database");
                    System.out.println("B. Read drug info from database");
                    System.out.println("C. Write drug info to text file");
                    System.out.println("D. Read drug info from text file");
                    System.out.print("Enter choice: ");

                    String drugChoice = in.nextLine().toUpperCase();

                    switch (drugChoice) {
                        case "A":
                            // writeDrugDB();
                            System.out.println("Writing drug info to DB...");
                            break;

                        case "B":
                            // readDrugDB();
                            System.out.println("Reading drug info from DB...");
                            break;

                        case "C":
                            // writeDrugFile();
                            System.out.println("Writing drug info to file...");
                            break;

                        case "D":
                            // readDrugFile();
                            System.out.println("Reading drug info from file...");
                            break;

                        default:
                            System.out.println("Invalid drug menu choice.");
                            break;

                    }
                    break;

                case "X":
                    System.out.println("Exiting program...");
                    return;

                default:
                    System.out.println("Invalid main menu choice.");
                    break;
            }
        }
    }

    // Method to write patient to database
    public static void writePateintDB() {

        Scanner in = new Scanner(System.in);

        while (true) {

            System.out.println("\nPatient Database Menu");
            System.out.println("A. Insert new patient");
            System.out.println("B. Exit");
            System.out.print("Enter choice: ");

            String choice = in.nextLine().toUpperCase();

            switch (choice) {

                case "A":
                    // Id auto generated by postgres

                    System.out.print("Enter patient first name: ");
                    String patientFirstName = in.nextLine();

                    System.out.print("Enter patient last name: ");
                    String patientLastName = in.nextLine();

                    System.out.print("Enter patient date of birth (yyyy-mm-dd): ");
                    String patientDOB = in.nextLine();

                    String query = """
                        INSERT INTO patients (patientFirstName, patientLastName, patientDOB)
                        VALUES (?, ?, ?)
                    """;

                    try {
                        Connection con = DatabaseConnection.getCon();

                        if (con == null) {
                            System.out.println("Database connection failed");
                            break;
                        }

                        PreparedStatement statement = con.prepareStatement(query);
                        statement.setString(1, patientFirstName);
                        statement.setString(2, patientLastName);
                        statement.setString(3, patientDOB);

                        int rows = statement.executeUpdate();
                        System.out.println("Inserted: " + rows + " row(s) successfully");

                        con.close();

                    } catch (SQLException e) {
                        System.out.println("Error inserting patient");
                        e.printStackTrace();
                    }

                    break;

                case "B":
                    System.out.println("Exiting patient database menu...");
                    return;

                default:
                    System.out.println("Invalid choice.");
                    break;
            }
        }
    }

    // Method to read patients from database
    public static void readDB() {

        ArrayList<Patient> patientList = new ArrayList<>();
        String query = "SELECT * FROM patients";

        try {
            Connection con = DatabaseConnection.getCon();
            PreparedStatement statement = con.prepareStatement(query);
            ResultSet res = statement.executeQuery();

            while (res.next()) {

                Patient temp = new Patient();
                temp.setPatientFirstName(res.getString("patientFirstName"));
                temp.setPatientLastName(res.getString("patientLastName"));
                temp.setPatientDOB(res.getString("patientDOB"));
                patientList.add(temp);
            }
            con.close();

        } catch (SQLException e) {

            e.printStackTrace();
        }

        for (Patient p : patientList) {
            System.out.println(p);
        }
    }
}
