
import java.io.FileReader;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Scanner;

public class Demo {

    public static void main(String[] args) {

        Scanner in = new Scanner(System.in);

        while (true) {

            // ===== MAIN MENU =====
            System.out.println("\n==== Main Menu ====");
            System.out.println("P. Patient Menu");
            System.out.println("D. Drug Menu");
            System.out.println("X. Exit");
            System.out.print("Enter choice: ");

            String choice = in.nextLine().toUpperCase();

            switch (choice) {

                // Menu if pateint option chosen
                case "P":
                    System.out.println("\n==== Patient Menu ====");
                    System.out.println("A. Write patient info to database");
                    System.out.println("B. Read patient info from database");
                    System.out.println("C. Write patient info to text file");
                    System.out.println("D. Read patient info from text file");
                    System.out.print("Enter choice: ");

                    String patientChoice = in.nextLine().toUpperCase();

                    switch (patientChoice) {

                        case "A":
                            writePatientDB();
                            break;

                        case "B":
                            readPatientDB();
                            break;

                        case "C":
                            writePatientFile();
                            break;

                        case "D":
                            readPatientFile();
                            break;

                        default:
                            break;
                    }
                    break;

                // Menu if drug option chosen
                case "D":
                    System.out.println("\n==== Drug Menu ====");
                    System.out.println("A. Write drug info to database");
                    System.out.println("B. Read drug info from database");
                    System.out.println("C. Write drug info to text file");
                    System.out.println("D. Read drug info from text file");
                    System.out.print("Enter choice: ");

                    String drugChoice = in.nextLine().toUpperCase();

                    switch (drugChoice) {
                        case "A":
                            writeDrugDB();
                            break;

                        case "B":
                            readDrugDB();
                            break;

                        case "C":
                            writeDrugFile();
                            break;

                        case "D":
                            readDrugFile();
                            break;

                        default:
                            break;

                    }
                    break;

                case "X":
                    System.out.println("Exiting program...");
                    return;

                default:
                    System.out.println("Invalid main menu choice.");
                    break;
            }
        }
    }

    // Method to write patient to database
    public static void writePatientDB() {

        Scanner in = new Scanner(System.in);

        while (true) {

            System.out.println("\nPatient Database Menu");
            System.out.println("A. Insert new patient");
            System.out.println("B. Exit");
            System.out.print("Enter choice: ");

            String choice = in.nextLine().toUpperCase();

            switch (choice) {

                case "A":
                    // Id auto generated by postgres

                    System.out.print("Enter patient first name: ");
                    String patientFirstName = in.nextLine();

                    System.out.print("Enter patient last name: ");
                    String patientLastName = in.nextLine();

                    System.out.print("Enter patient date of birth (yyyy-mm-dd): ");
                    String patientDOB = in.nextLine();

                    String query = """
                        INSERT INTO patients (patientFirstName, patientLastName, patientDOB)
                        VALUES (?, ?, ?)
                    """;

                    try {
                        Connection con = DatabaseConnection.getCon();

                        if (con == null) {
                            System.out.println("Database connection failed");
                            break;
                        }

                        PreparedStatement statement = con.prepareStatement(query);
                        statement.setString(1, patientFirstName);
                        statement.setString(2, patientLastName);
                        statement.setDate(3, java.sql.Date.valueOf(patientDOB));

                        int rows = statement.executeUpdate();
                        System.out.println("Inserted: " + rows + " row(s) successfully");

                        con.close();

                    } catch (SQLException e) {
                        System.out.println("Error inserting patient");
                        e.printStackTrace();
                    }

                    break;

                case "B":
                    System.out.println("Exiting patient database menu...");
                    return;

                default:
                    System.out.println("Invalid choice.");
                    break;
            }
        }
    }

    // Method to read patients from database
    public static void readPatientDB() {

        ArrayList<Patient> patientList = new ArrayList<>();
        String query = "SELECT * FROM patients";

        try {
            Connection con = DatabaseConnection.getCon();
            PreparedStatement statement = con.prepareStatement(query);
            ResultSet res = statement.executeQuery();

            while (res.next()) {

                Patient temp = new Patient();
                temp.setPatientId(res.getInt("patientid"));
                temp.setPatientFirstName(res.getString("patientfirstname"));
                temp.setPatientLastName(res.getString("patientlastname"));
                temp.setPatientDOB(res.getString("patientdob"));
                patientList.add(temp);
            }
            con.close();

        } catch (SQLException e) {

            e.printStackTrace();
        }

        for (Patient p : patientList) {
            System.out.println(p);
        }
    }

    // Method to write patient to text file
    public static void writePatientFile() {

        Scanner in = new Scanner(System.in);

        System.out.print("Enter patient ID: ");
        String id = in.nextLine();

        System.out.print("Enter patient first name: ");
        String firstName = in.nextLine();

        System.out.print("Enter patient last name: ");
        String lastName = in.nextLine();

        System.out.print("Enter patient date of birth (yyyy-mm-dd): ");
        String dob = in.nextLine();

        String line = id + "," + firstName + "," + lastName + "," + dob;

        try {
            FileWriter writer = new FileWriter("patients.txt", true);
            writer.write(line + "\n");
            writer.close();

            System.out.println("Patient written to file successfully.");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Method to read patients from text file
    public static void readPatientFile() {

        try {
            FileReader fr = new FileReader("patients.txt");
            int i;

            while ((i = fr.read()) != -1) {
                System.out.print((char) i);
            }

            fr.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Method to write drug to database
    public static void writeDrugDB() {

        Scanner in = new Scanner(System.in);

        while (true) {

            System.out.println("\nDrug Database Menu");
            System.out.println("A. Insert new drug");
            System.out.println("B. Exit");
            System.out.print("Enter choice: ");

            String choice = in.nextLine().toUpperCase();

            switch (choice) {

                case "A":
                    // id auto generated by postgres

                    System.out.println("Enter drug name: ");
                    String drugName = in.nextLine();

                    System.out.println("Enter drug cost: ");
                    double drugCost = in.nextDouble();
                    in.nextLine();

                    System.out.println("Enter drug dosage: ");
                    double dosage = in.nextDouble();
                    in.nextLine();

                    String query = """
                            INSERT INTO drugs (drugName, drugCost, dosage)
                            VALUES(?, ?, ?)
                            """;

                    try {
                        Connection con = DatabaseConnection.getCon();

                        if (con == null) {
                            System.out.println("Database connection failed");
                            break;
                        }

                        PreparedStatement statement = con.prepareStatement(query);
                        statement.setString(1, drugName);
                        statement.setDouble(2, drugCost);
                        statement.setDouble(3, dosage);

                        int rows = statement.executeUpdate();
                        System.out.println("Inserted: " + rows + " row(s) successfully");

                        con.close();

                    } catch (SQLException e) {
                        System.out.println("Error inserting drug");
                        e.printStackTrace();
                    }

                    break;

                case "B":
                    System.out.println("Exiting drug database menu...");
                    return;

                default:
                    System.out.println("Invalid choice.");
                    break;
            }

        }

    }

    // Method to read drugs from database
    public static void readDrugDB() {
        ArrayList<Drug> drugList = new ArrayList<>();
        String query = "SELECT * FROM drugs";

        try {
            Connection con = DatabaseConnection.getCon();
            PreparedStatement statement = con.prepareStatement(query);
            ResultSet res = statement.executeQuery();

            while (res.next()) {

                Drug temp = new Drug();
                temp.setDrugId(res.getInt("drugid"));
                temp.setDrugName(res.getString("drugname"));
                temp.setDrugCost(res.getDouble("drugcost"));
                temp.setDosage(res.getDouble("dosage"));
                drugList.add(temp);
            }
            con.close();

        } catch (SQLException e) {

            e.printStackTrace();
        }

        for (Drug d : drugList) {
            System.out.println(d);
        }
    }

    // Method to write drug to a text file
    public static void writeDrugFile() {

        Scanner in = new Scanner(System.in);

        System.out.print("Enter drug ID: ");
        String id = in.nextLine();

        System.out.print("Enter drug name: ");
        String drugName = in.nextLine();

        System.out.print("Enter drug cost: ");
        double drugCost = in.nextDouble();
        in.nextLine();

        System.out.print("Enter drug dosage: ");
        double dosage = in.nextDouble();
        in.nextLine();

        String line = id + "," + drugName + "," + drugCost + "," + dosage;

        try {
            FileWriter writer = new FileWriter("drugs.txt", true);
            writer.write(line + "\n");
            writer.close();

            System.out.println("Drug written to file successfully.");

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    // Method to read drugs from text file
    public static void readDrugFile() {

        try {
            FileReader fr = new FileReader("drugs.txt");
            int i;

            while ((i = fr.read()) != -1) {
                System.out.print((char) i);
            }

            fr.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
